import type { Memory } from '../types';

/**
 * Default Celestial Memories Seed Configuration.
 * Defines positions, types, colors, and content for the 12 3D Universe stars.
 */
export const memories: Memory[] = [
  {
    id: 'memory-01',
    type: 'text',
    celestialType: 'star',
    title: 'First Light',
    date: 'Cosmic Beginning',
    description: 'A glowing star marking the initial spark of our shared universe.',
    color: '#4fc3f7',
    position: { x: -8, y: 5, z: -25 },
    scale: 1.2,
    animationStyle: 'pulse',
    unlockCondition: { type: 'always', value: 0 },
  },
  {
    id: 'memory-02',
    type: 'text',
    celestialType: 'planet',
    title: 'Cosmic Whisper',
    date: 'Starlight Phase',
    description: 'Echoes of quiet conversations drifting across space.',
    color: '#ab47bc',
    position: { x: 12, y: -4, z: -35 },
    scale: 1.1,
    animationStyle: 'orbit',
    unlockCondition: { type: 'always', value: 0 },
  },
  {
    id: 'memory-03',
    type: 'photo',
    celestialType: 'constellation',
    title: 'Starlight Promises',
    date: 'Nebula Phase',
    description: 'Bright points of light bound together into an unforgettable pattern.',
    color: '#ffb74d',
    position: { x: -15, y: -8, z: -45 },
    scale: 1.3,
    animationStyle: 'breathe',
    unlockCondition: { type: 'discoveredCount', value: 1 },
  },
  {
    id: 'memory-04',
    type: 'text',
    celestialType: 'nebula',
    title: 'Deep Nebula',
    date: 'Luminous Phase',
    description: 'A vibrant cloud of cosmic dust radiating warmth and magic.',
    color: '#e91e63',
    position: { x: 6, y: 14, z: -55 },
    scale: 1.4,
    animationStyle: 'float',
    unlockCondition: { type: 'discoveredCount', value: 2 },
  },
  {
    id: 'memory-05',
    type: 'text',
    celestialType: 'star',
    title: 'Orbit of Us',
    date: 'Gravitational Phase',
    description: 'Two paths curving around each other in gravitational harmony.',
    color: '#81c784',
    position: { x: -22, y: 10, z: -65 },
    scale: 1.1,
    animationStyle: 'spin',
    unlockCondition: { type: 'discoveredCount', value: 3 },
  },
  {
    id: 'memory-06',
    type: 'text',
    celestialType: 'capsule',
    title: 'Time Capsule',
    date: 'Stasis Phase',
    description: 'A preserved moment suspended in timeless crystal energy.',
    color: '#26c6da',
    position: { x: 18, y: 12, z: -75 },
    scale: 1.2,
    animationStyle: 'pulse',
    unlockCondition: { type: 'discoveredCount', value: 4 },
  },
  {
    id: 'memory-07',
    type: 'audio',
    celestialType: 'mystery',
    title: 'Midnight Rain',
    date: 'Atmospheric Phase',
    description: 'Gentle melodies falling like starlight on a quiet night.',
    color: '#7e57c2',
    position: { x: -10, y: -18, z: -85 },
    scale: 1.3,
    animationStyle: 'breathe',
    unlockCondition: { type: 'discoveredCount', value: 5 },
  },
  {
    id: 'memory-08',
    type: 'text',
    celestialType: 'portal',
    title: 'Eternal Echoes',
    date: 'Singularity Phase',
    description: 'A gateway leading into deeper layers of cosmic memory.',
    color: '#ff7043',
    position: { x: 25, y: -12, z: -95 },
    scale: 1.4,
    animationStyle: 'spin',
    unlockCondition: { type: 'discoveredCount', value: 6 },
  },
  {
    id: 'memory-09',
    type: 'text',
    celestialType: 'star',
    title: 'Solemn Constellation',
    date: 'Reflection Phase',
    description: 'A serene star reflecting deep thoughts and quiet moments.',
    color: '#64b5f6',
    position: { x: -5, y: 22, z: -105 },
    scale: 1.2,
    animationStyle: 'pulse',
    unlockCondition: { type: 'discoveredCount', value: 7 },
  },
  {
    id: 'memory-10',
    type: 'text',
    celestialType: 'constellation',
    title: 'Celestial Convergence',
    date: 'Alignment Phase',
    description: 'Multiple lines of light converging into a single brilliant beacon.',
    color: '#f06292',
    position: { x: 15, y: -25, z: -115 },
    scale: 1.3,
    animationStyle: 'breathe',
    unlockCondition: { type: 'discoveredCount', value: 8 },
  },
  {
    id: 'memory-11',
    type: 'text',
    celestialType: 'star',
    title: 'Cosmic Horizon',
    date: 'Expansion Phase',
    description: 'Looking outward toward endless possibilities beyond the edge.',
    color: '#ffd54f',
    position: { x: -28, y: -6, z: -125 },
    scale: 1.2,
    animationStyle: 'orbit',
    unlockCondition: { type: 'discoveredCount', value: 9 },
  },
  {
    id: 'memory-12',
    type: 'text',
    celestialType: 'star',
    title: 'The Final Star',
    date: 'Radiant Phase',
    description: 'The 12th star completed — unlocking the central core of the Universe.',
    color: '#4dd0e1',
    position: { x: 0, y: 0, z: -135 },
    scale: 1.5,
    animationStyle: 'pulse',
    unlockCondition: { type: 'discoveredCount', value: 11 },
  },
];

export const constellationConnections: Array<[string, string]> = [
  ['memory-01', 'memory-02'],
  ['memory-02', 'memory-03'],
  ['memory-03', 'memory-04'],
  ['memory-04', 'memory-05'],
  ['memory-05', 'memory-06'],
  ['memory-06', 'memory-07'],
  ['memory-07', 'memory-08'],
  ['memory-08', 'memory-09'],
  ['memory-09', 'memory-10'],
  ['memory-10', 'memory-11'],
  ['memory-11', 'memory-12'],
];
